spring.application.name=indexer
server.port=${PORT:8080}
indexer.lucene-ram-limit=200
indexer.buffer-duration=1s
indexer.stored-fields=rkey,did,createdAt,known_lang,error

spring.threads.virtual.enabled=true
