spring.application.name=indexer
server.port=${PORT:8080}
indexer.lucene-ram-limit=200
indexer.stored-fields=rkey,did,createdAt,known_lang,error
indexer.jetstream-history=30m
indexer.jetstream-compression=true
indexer.buffer-duration=5s
indexer.buffer-capacity=500
indexer.buffer-wakeness=200

spring.threads.virtual.enabled=true
