name: Build and Push Docker Image

on:
  push:
    branches: [ latest ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: push
        run: ./gradlew bootBuildImage --imageName=ghcr.io/${{ github.repository }} --publishImage --no-daemon

      - name: Redeploy render.com service
        env:
          URL: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: curl "$URL"
