name: Build and Push Docker Image

on:
  push:
    branches: [ latest ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Restore Docker Build Cache
        id: restore_cache
        uses: BYK/docker-volume-cache-action/restore@main
        with:
          key: docker-volumes-${{ hashFiles('build.gradle.kts') }}
          volumes: |
            build-cache

      - name: Build and push Docker image
        id: push
        run: ./gradlew bootBuildImage --imageName=ghcr.io/${{ github.repository }} --publishImage

      - name: Save Docker Build Cache
        uses: BYK/docker-volume-cache-action/save@main
        with:
          key: ${{ steps.restore_cache.outputs.cache-primary-key }}
          volumes: |
            build-cache
